# Site settings
title: Melody's Blog
SEOTitle: Melody's Blog | 一个嵌入式大学生的学习笔记
header-img: img/home-bg.jpg
email: your-email@example.com
description: "这里是 Melody 的个人博客，记录一个嵌入式大学生的学习与成长。"
keyword: "Melody, 博客, 嵌入式, 大学生, 学习笔记, 技术分享"
url: "https://your-username.github.io" # Change to your actual GitHub Pages URL
baseurl: ""

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: your-weibo-username
zhihu_username: your-zhihu-username
github_username: your-github-username
twitter_username: your-twitter-username

# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true
plugins: [jekyll-paginate]

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: your-disqus-username

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-xxxxxx-x" # Change to your actual Google Analytics ID
ga_domain: "your-blog-domain.com" # Change to your actual domain

# Sidebar settings
sidebar: true
sidebar-about-description: "记录一个热爱嵌入式的大学生的学习与成长。"
sidebar-avatar: https://github.com/your-github-username.png # Change to your GitHub username

# Featured Tags
featured-tags: true
featured-condition-size: 1

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "Github", href: "https://github.com/" },
    { title: "嵌入式学习", href: "https://www.your-favorite-embedded-site.com" },
    # Add more friends here
  ]
